-- Strategy Signals Log Table
-- Records every signal generated by _afternoon_check.py
-- regardless of whether the trade was executed

CREATE TABLE IF NOT EXISTS strategy_signals (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    trade_date DATE NOT NULL,
    signal_type VARCHAR(10) NOT NULL COMMENT 'buyA/buyB/sell_all/stop_loss/stop_ma/sell_half',
    sentiment_value DECIMAL(5,2) COMMENT 'sentiment at trigger time',
    nav DECIMAL(10,4) COMMENT 'ETF nav at trigger time',
    reason VARCHAR(200) COMMENT 'trigger reason description',
    executed TINYINT(1) DEFAULT 0 COMMENT '0=signal only (not traded), 1=executed',
    create_time DATETIME DEFAULT NOW(),
    UNIQUE KEY uk_date_type (trade_date, signal_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
